### ISSUE TITLE
iosColors.addObject is not a function

### ISSUE THREAD

**Issue by shiv19** [NativeScript/ns-v8ios-runtime#21]
```
2020-01-20 14:40:04.511370+0530 GFConnectNS[59188:4094569] CONSOLE ERROR: {
  "context": "__onDiscardedError",
  "keys": "stackTrace"
}
2020-01-20 14:40:04.512174+0530 GFConnectNS[59188:4094569] CONSOLE ERROR: Error Domain=undefined@undefined:undefined Code=-6661 "(null)" UserInfo={msg=TypeError: iosColors.addObject is not a function, stackTrace=	(file:///app/vendor.js:32966:19)
	at drawGradient(file:///app/vendor.js:32965:25)
	at createBackgroundUIColor(file:///app/vendor.js:32445:13)
	at (file:///app/vendor.js:25210:30)
	at (file:///app/vendor.js:20517:18)
	at (file:///app/vendor.js:20508:14)
	at (file:///app/vendor.js:20054:15)
	at (file:///app/vendor.js:19787:34)
	at (file:///app/vendor.js:27851:43)
	at (file:///app/vendor.js:20505:18)
	at (file:///app/vendor.js:20054:15)
	at (file:///app/vendor.js:19787:34)
	at (file:///app/vendor.js:30513:28)
	at (file:///app/vendor.js:20505:18)
	at (file:///app/vendor.js:20054:15)
	at layoutView(file:///app/vendor.js:20185:41)
	at (file:///app/vendor.js:30404:24)
}
```

I noticed this from xcode logs

**Comment by darind** [comment]
We have released a fix. When you get the chance, could you please verify if this error is still occurring?

**Comment by darind** [comment]
Closing the issue for inactivity. Please re-open if the issue persists or manifests under some other form.
