### ISSUE TITLE
Xcode version 15.3 + iOS 17 + MacOSX sumona 14.5 facing issue to configure or install nativescript, tns 6.5.6

### ISSUE THREAD

**Issue by HoncoTech** [NativeScript/ns-v8ios-runtime#253]
sudo npm install -g nativescript --unsafe-perm
npm WARN deprecated osenv@0.1.5: This package is no longer supported.
npm WARN deprecated phin@2.9.3: Package no longer supported. Contact Support at https://www.npmjs.com/support for more info.
npm WARN deprecated read-package-json@6.0.4: This package is no longer supported. Please use @npmcli/package-json instead.
npm WARN deprecated npmlog@6.0.2: This package is no longer supported.
npm WARN deprecated are-we-there-yet@3.0.1: This package is no longer supported.
npm WARN deprecated gauge@4.0.4: This package is no longer supported.
npm WARN deprecated osenv@0.1.4: This package is no longer supported.

> nativescript@8.7.1 preuninstall /Users/XXXXX/.nvm/versions/node/v14.18.0/lib/node_modules/nativescript
> node preuninstall.js

/Users/XXXXX/.nvm/versions/node/v14.18.0/lib/node_modules/nativescript/node_modules/@npmcli/agent/lib/agents.js:108
    options.lookup ??= this.#options.lookup
                   ^^^

SyntaxError: Unexpected token '??='
    at wrapSafe (internal/modules/cjs/loader.js:1001:16)
    at Module._compile (internal/modules/cjs/loader.js:1049:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:93:18)
    at Object.<anonymous> (/Users/XXXXX/.nvm/versions/node/v14.18.0/lib/node_modules/nativescript/node_modules/@npmcli/agent/lib/index.js:7:15)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
/Users/XXXXX/.nvm/versions/node/v14.18.0/bin/tns -> /Users/XXXXX/.nvm/versions/node/v14.18.0/lib/node_modules/nativescript/bin/tns
/Users/XXXXX/.nvm/versions/node/v14.18.0/bin/ns -> /Users/XXXXX/.nvm/versions/node/v14.18.0/lib/node_modules/nativescript/bin/tns
/Users/XXXXX/.nvm/versions/node/v14.18.0/bin/nativescript -> /Users/XXXXX/.nvm/versions/node/v14.18.0/lib/node_modules/nativescript/bin/tns
/Users/XXXXX/.nvm/versions/node/v14.18.0/bin/nsc -> /Users/XXXXX/.nvm/versions/node/v14.18.0/lib/node_modules/nativescript/bin/tns

> nativescript@8.7.1 postinstall /Users/XXXXX/.nvm/versions/node/v14.18.0/lib/node_modules/nativescript
> node postinstall.js

/Users/XXXXX/.nvm/versions/node/v14.18.0/lib/node_modules/nativescript/node_modules/@npmcli/agent/lib/agents.js:108
    options.lookup ??= this.#options.lookup
                   ^^^

SyntaxError: Unexpected token '??='
    at wrapSafe (internal/modules/cjs/loader.js:1001:16)
    at Module._compile (internal/modules/cjs/loader.js:1049:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:93:18)
    at Object.<anonymous> (/Users/XXXXX/.nvm/versions/node/v14.18.0/lib/node_modules/nativescript/node_modules/@npmcli/agent/lib/index.js:7:15)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
npm WARN notsup Unsupported engine for @npmcli/arborist@7.5.2: wanted: {"node":"^16.14.0 || >=18.0.0"} (current: {"node":"14.18.0","npm":"6.14.15"})
npm WARN notsup Not compatible with your version of node/npm: @npmcli/arborist@7.5.2
npm WARN notsup Unsupported engine for pacote@18.0.6: wanted: {"node":"^16.14.0 || >=18.0.0"} (current: {"node":"14.18.0","npm":"6.14.15"})

**Comment by HoncoTech** [comment]
Installing node 16 and Also softlinking python and python 3 solved the issue.

**Comment by HoncoTech** [comment]
Closing the issue
