### ISSUE TITLE
crash 

### ISSUE THREAD

**Issue by farfromrefug** [NativeScript/ns-v8ios-runtime#32]
here is a crash i get while starting another app of mine.

Using 6.5.0-beta.2-v8-2020-02-24-132159-02

here is the related code:
```ts
initNativeView() {
        super.initNativeView();
        this._observer = ObserverClass.alloc();
        this._observer['_owner'] = new WeakRef(this);
        this.nativeViewProtected.addObserverForKeyPathOptionsContext(this._observer, 'contentSize', NSKeyValueObservingOptions.New, null);
    }
```
Happens on the `addObserverForKeyPathOptionsContext` line.
```
====== Assertion failed ======
Native stack trace:
1          0x10a08f29b tns::Assert(bool, v8::Isolate*) + 119
2          0x10a0b2c94 tns::Interop::WriteValue(v8::Local<v8::Context>, tns::TypeEncoding const*, void*, v8::Local<v8::Value>) + 5188
3          0x10a0b1728 tns::Interop::SetFFIParams(v8::Local<v8::Context>, tns::TypeEncoding const*, tns::FFICall*, int, int, tns::V8Args&) + 110
4          0x10a0b13ac tns::Interop::CallFunctionInternal(tns::MethodCall&) + 312
5          0x109ffc57f tns::ArgConverter::Invoke(v8::Local<v8::Context>, objc_class*, v8::Local<v8::Object>, tns::V8Args&, tns::MethodMeta const*, bool) + 741
6          0x10a05588e tns::MetadataBuilder::InvokeMethod(v8::Local<v8::Context>, tns::MethodMeta const*, v8::Local<v8::Object>, tns::V8Args&, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, bool) + 76
7          0x10a05516f tns::MetadataBuilder::MethodCallback(v8::FunctionCallbackInfo<v8::Value> const&) + 219
8          0x10a1c25ac v8::internal::FunctionCallbackArguments::Call(v8::internal::CallHandlerInfo) + 620
9          0x10a1c1a5c v8::internal::MaybeHandle<v8::internal::Object> v8::internal::(anonymous namespace)::HandleApiCallHelper<false>(v8::internal::Isolate*, v8::internal::Handle<v8::internal::HeapObject>, v8::internal::Handle<v8::internal::HeapObject>, v8::internal::Handle<v8::internal::FunctionTemplateInfo>, v8::internal::Handle<v8::internal::Object>, v8::internal::BuiltinArguments) + 556
10         0x10a1c10d3 v8::internal::Builtin_Impl_HandleApiCall(v8::internal::BuiltinArguments, v8::internal::Isolate*) + 259
11         0x10aa40819 Builtins_CEntry_Return1_DontSaveFPRegs_ArgvOnStack_BuiltinExit + 57
12         0x10a9d9339 Builtins_InterpreterEntryTrampoline + 185
JavaScript stack trace:
at push.../node_modules/.pnpm/registry.npmjs.org/nativescript-material-button/3.1.10/node_modules/nativescript-material-button/button.js.Button.initNativeView (file:///app/vendor.js:77376:34)
at push.../node_modules/.pnpm/registry.npmjs.org/@nativescript/core/6.4.2/node_modules/@nativescript/core/ui/core/view-base/view-base.js.ViewBase.setNativeView (file:///app/vendor.js:18485:18)
at push.../node_modules/.pnpm/registry.npmjs.org/@nativescript/core/6.4.2/node_modules/@nativescript/core/ui/core/view-base/view-base.js.ViewBase._setupUI (file:///app/vendor.js:18464:14)
at <anonymous> (file:///app/vendor.js:18471:19)
at push.../node_modules/.pnpm/registry.npmjs.org/@nativescript/core/6.4.2/node_modules/@nativescript/core/ui/layouts/layout-base-common.js.LayoutBaseCommon.eachChildView (file:///app/vendor.js:28263:26)
at push.../node_modules/.pnpm/registry.npmjs.org/@nativescript/core/6.4.2/node_modules/@nativescript/core/ui/core/view/view-common.js.ViewCommon.eachChild (file:///app/vendor.js:19649:14)
at <…>

```
Let me if i can give more data

**Comment by darind** [comment]
Replace:

```javascript
this._observer = ObserverClass.alloc();
```

with:

```javascript
this._observer = ObserverClass.alloc().init();
```

The old runtime was applying some heuristics to non-initialized objects to find the most appropriate initializer.

The new runtime doesn't do this anymore and the developer needs to initialize his objects, just like you would do in objective-c.
