### ISSUE TITLE
crash when fetching v8

### ISSUE THREAD

**Issue by IEFX** [NativeScript/ns-v8ios-runtime#47]
fetch v8
Running: gclient root
Warning: Running gclient on Python 3.
If you encounter any issues, please file a bug on crbug.com under the Infra>SDK component.
Running: gclient config --spec 'solutions = [
  {
    "name": "v8",
    "url": "https://chromium.googlesource.com/v8/v8.git",
    "deps_file": "DEPS",
    "managed": False,
    "custom_deps": {},
  },
]
'
Warning: Running gclient on Python 3.
If you encounter any issues, please file a bug on crbug.com under the Infra>SDK component.
Running: gclient sync --with_branch_heads
Warning: Running gclient on Python 3.
If you encounter any issues, please file a bug on crbug.com under the Infra>SDK component.

________ running 'git -c core.deltaBaseCacheLimit=2g clone --no-checkout --progress https://chromium.googlesource.com/v8/v8.git /Users/darrylbarnes/ns-v8ios-runtime/_gclient_v8_rdbnefku' in '/Users/../ns-v8ios-runtime'
Cloning into '/Users/../ns-v8ios-runtime/_gclient_v8_rdbnefku'...
remote: Sending approximately 329.31 MiB ...
remote: Counting objects: 7667, done
remote: Finding sources: 100% (7/7)
remote: Total 763243 (delta 647095), reused 763239 (delta 647095)
Receiving objects: 100% (763243/763243), 329.31 MiB | 29.39 MiB/s, done.
Resolving deltas: 100% (647095/647095), done.

[0:01:10] Still working on:
[0:01:10]   v8
1>Syncing projects:   0% ( 0/ 2)
[0:01:13] Still working on:
[0:01:13]   v8
Syncing projects: 100% (29/29), done.
Running hooks:  16% ( 4/25) clang_format_mac
________ running 'download_from_google_storage --no_resume --platform=darwin --no_auth --bucket chromium-clang-format -s v8/buildtools/mac/clang-format.sha1' in '/Users/darrylbarnes/ns-v8ios-runtime'
Failed to fetch file gs://chromium-clang-format/62bde1baa7196ad9df969fc1f06b66360b1a927b for v8/buildtools/mac/clang-format. [Err: Traceback (most recent call last):
  File "/Users/darrylbarnes/ns-v8ios-runtime/depot_tools/gsutil.py", line 190, in <module>
    sys.exit(main())
  File "/Users/darrylbarnes/ns-v8ios-runtime/depot_tools/gsutil.py", line 186, in main
    clean=args.clean)
  File "/Users/darrylbarnes/ns-v8ios-runtime/depot_tools/gsutil.py", line 134, in run_gsutil
    gsutil_bin = ensure_gsutil(force_version, target, clean)
  File "/Users/darrylbarnes/ns-v8ios-runtime/depot_tools/gsutil.py", line 113, in ensure_gsutil
    target_zip_filename = download_gsutil(version, instance_dir)
  File "/Users/darrylbarnes/ns-v8ios-runtime/depot_tools/gsutil.py", line 70, in download_gsutil
    u = urllib.urlopen(url)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 429, in open
    response = self._open(req, data)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 447, in _open
    '_open', req)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 1241, in https_open
    context=self._context)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 1198, in do_open
    raise URLError(err)
urllib2.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:661)>
]
0> Failed to fetch file gs://chromium-clang-format/62bde1baa7196ad9df969fc1f06b66360b1a927b for v8/buildtools/mac/clang-format, skipping. [Err: Traceback (most recent call last):
  File "/Users/darrylbarnes/ns-v8ios-runtime/depot_tools/gsutil.py", line 190, in <module>
    sys.exit(main())
  File "/Users/darrylbarnes/ns-v8ios-runtime/depot_tools/gsutil.py", line 186, in main
    clean=args.clean)
  File "/Users/darrylbarnes/ns-v8ios-runtime/depot_tools/gsutil.py", line 134, in run_gsutil
    gsutil_bin = ensure_gsutil(force_version, target, clean)
  File "/Users/darrylbarnes/ns-v8ios-runtime/depot_tools/gsutil.py", line 113, in ensure_gsutil
    target_zip_filename = download_gsutil(version, instance_dir)
  File "/Users/darrylbarnes/ns-v8ios-runtime/depot_tools/gsutil.py", line 70, in download_gsutil
    u = urllib.urlopen(url)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 429, in open
    response = self._open(req, data)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 447, in _open
    '_open', req)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 1241, in https_open
    context=self._context)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 1198, in do_open
    raise URLError(err)
urllib2.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:661)>
]
Downloading 1 files took 0.715730 second(s)
Error: Command 'download_from_google_storage --no_resume --platform=darwin --no_auth --bucket chromium-clang-format -s v8/buildtools/mac/clang-format.sha1' returned non-zero exit status 1 in /Users/../ns-v8ios-runtime
Subprocess failed with return code 2.

**Comment by NathanaelA** [comment]
`fetch` (from the `depo_tools`) are all a google product, and its download system to fetch/sync the v8 from the google v8 repo.   We have no control over any failures of any of google's `depo_tools`.

You may want to try again.  And hopefully it will work.  However, v8 is massive amount of source and third party dependencies so if you have poor internet or slow internet that may disconnect; you might have to fetch & sync multiple times before you get everything...

If it still fails to work, and you know it isn't related to your internet; you need to put a bug report on Google's crbug.com about anything depo_tools related..
